sonar.projectKey=WGrav01_OpenCIQ
sonar.organization=wgrav


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=OpenCIQ
#sonar.projectVersion=1.0

sonar.sources=./src/,./.forgejo,./.cargo/,./Cargo.toml,./Cargo.lock,./rust-toolchain.toml,./clippy.toml,./rustfmt.toml

# Yoink out build artifacts
sonar.exclusions=**/target/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Code coverage format
sonar.rust.lcov.reportPaths=./lcov.info
