name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: debian-bookworm # Self hosted runner

    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Cache Rust
        id: cache-rust
        uses: https://code.forgejo.org/actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Rust
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy,llvm-tools-preview

      - name: Install cargo-llvm-cov
        if: steps.cache-rust.outputs.cache-hit != 'true'
        uses: https://github.com/taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        if: steps.cache-rust.outputs.cache-hit != 'true'
        uses: https://github.com/taiki-e/install-action@nextest

      - name: Run tests and collect coverage data
        run: cargo llvm-cov nextest --profile ci

      - name: Generate LCOV report
        run: cargo llvm-cov --lcov --output-path lcov.info

      - name: SonarQube Upload And Scan
        if: ${{ !cancelled() }}
        uses: https://github.com/SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: --define sonar.rust.lcov.reportPaths=./lcov.info
