name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: codeberg-tiny

    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v4

      - name: Set up Rust
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: https://github.com/taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        uses: https://github.com/taiki-e/install-action@nextest

      - name: Collect coverage data
        run: cargo llvm-cov nextest --profile ci

      - name: Generate LCOV report
        run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload Test Results to Trunk.io
        if: ${{ !cancelled() }} # Upload the results even if the tests fail
        continue-on-error: true # don't fail this job if the upload fails
        uses: https://github.com/trunk-io/analytics-uploader@main
        with:
          junit-paths: "**/*.xml"
          org-slug: openciq
          token: ${{ secrets.TRUNK_API_TOKEN }}

      - name: Upload coverage data to codecov
        uses: https://github.com/codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
